export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#171c1f",
        "surface-container-highest": "#dfe3e7",
        "secondary-fixed": "#dde1ff",
        "surface-bright": "#f6fafe",
        "on-surface-variant": "#3d4a3e",
        "surface-container-low": "#f0f4f8",
        "on-error-container": "#93000a",
        "tertiary": "#a43c12",
        "on-primary-fixed-variant": "#005228",
        "surface-container-high": "#e4e9ed",
        "primary-fixed": "#6bfe9c",
        "on-tertiary-container": "#7f2700",
        "surface-container": "#eaeef2",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#001356",
        "outline": "#6c7b6d",
        "error-container": "#ffdad6",
        "outline-variant": "#bbcbbb",
        "on-primary": "#ffffff",
        "background": "#f6fafe",
        "primary": "#006d37",
        "surface-tint": "#006d37",
        "primary-fixed-dim": "#4ae183",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2c3134",
        "on-tertiary-fixed": "#380c00",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#171c1f",
        "surface-variant": "#dfe3e7",
        "on-secondary-container": "#354487",
        "primary-container": "#2ecc71",
        "secondary-container": "#a6b5ff",
        "surface-dim": "#d6dade",
        "secondary": "#4b5a9e",
        "tertiary-container": "#ff9873",
        "on-primary-container": "#005027",
        "inverse-primary": "#4ae183",
        "tertiary-fixed": "#ffdbcf",
        "on-primary-fixed": "#00210c",
        "on-secondary-fixed-variant": "#334284",
        "secondary-fixed-dim": "#b9c3ff",
        "inverse-on-surface": "#edf1f5",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb59c",
        "on-tertiary-fixed-variant": "#822800",
        "surface": "#f6fafe"
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
        "body-md": ["Plus Jakarta Sans"],
        "label-caps": ["Space Grotesk"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "500"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "700"}]
      },
      spacing: {
        "lg": "48px",
        "sm": "12px",
        "gutter": "24px",
        "base": "8px",
        "md": "24px",
        "xs": "4px",
        "margin": "32px",
        "xl": "80px"
      },
      backdropBlur: {
        glass: '16px',
      }
    },
  },
  plugins: [],
}
